import PDFDocument from 'pdfkit';
import { Response } from 'express';

export interface ReportPDFData {
  studentName: string;
  grade: string;
  reportDate: string;
  summary: {
    overallPerformance: string;
    keyStrengths: string[];
    areasNeedingAttention: string[];
    teacherHighlights: string[];
  };
  currentActivities?: string[];
  currentActivityEvaluations?: Array<{
    activityName: string;
    recommendation: 'continue' | 'reconsider' | 'stop';
    reasoning: string;
    alignment: number;
    alternatives?: string[];
  }>;
  recommendations?: Array<{
    name: string;
    category: string;
    priority: string;
    description: string;
    benefits: string[];
    frequency: string;
    estimatedCost: string;
    whyRecommended: string;
    targetedAttributes?: string[];
    venues?: Array<{
      name: string;
      address: string;
      distance?: string;
      phone?: string;
    }>;
  }>;
  location?: {
    address: string;
  };
}

export class PDFGeneratorService {
  /**
   * Generate a comprehensive PDF report with summary and recommendations
   */
  generateReportPDF(data: ReportPDFData, res: Response): void {
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: 50, bottom: 50, left: 50, right: 50 }
    });

    // Set response headers for PDF download
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="${data.studentName.replace(/\s+/g, '_')}_Report_${new Date().toISOString().split('T')[0]}.pdf"`
    );

    // Pipe PDF to response
    doc.pipe(res);

    // Add content
    this.addHeader(doc, data);
    this.addStudentInfo(doc, data);
    this.addSummary(doc, data);

    if (data.currentActivities && data.currentActivities.length > 0) {
      this.addCurrentActivities(doc, data);
    }

    if (data.currentActivityEvaluations && data.currentActivityEvaluations.length > 0) {
      this.addActivityEvaluations(doc, data);
    }

    if (data.recommendations && data.recommendations.length > 0) {
      this.addRecommendations(doc, data);
    }

    // Add footer to current (last) page before finalizing
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor('#95a5a6')
      .text(
        `Generated by Enhance Your Child - ${new Date().toLocaleDateString()}`,
        50,
        doc.page.height - 40,
        { align: 'center', width: doc.page.width - 100 }
      );

    // Finalize PDF
    doc.end();
  }

  private addHeader(doc: PDFKit.PDFDocument, data: ReportPDFData): void {
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor('#2c3e50')
      .text('Child Development Report', { align: 'center' })
      .moveDown(0.5);

    doc
      .fontSize(12)
      .font('Helvetica')
      .fillColor('#7f8c8d')
      .text('Enhance Your Child', { align: 'center' })
      .moveDown(1.5);

    // Add a line separator
    doc
      .strokeColor('#3498db')
      .lineWidth(2)
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .stroke()
      .moveDown(1);
  }

  private addStudentInfo(doc: PDFKit.PDFDocument, data: ReportPDFData): void {
    const startY = doc.y;

    doc
      .fontSize(10)
      .font('Helvetica-Bold')
      .fillColor('#2c3e50')
      .text('Student: ', 50, startY, { continued: true })
      .font('Helvetica')
      .fillColor('#34495e')
      .text(data.studentName);

    doc
      .font('Helvetica-Bold')
      .fillColor('#2c3e50')
      .text('Grade: ', 50, doc.y, { continued: true })
      .font('Helvetica')
      .fillColor('#34495e')
      .text(data.grade || 'Not specified');

    doc
      .font('Helvetica-Bold')
      .fillColor('#2c3e50')
      .text('Report Date: ', 50, doc.y, { continued: true })
      .font('Helvetica')
      .fillColor('#34495e')
      .text(new Date(data.reportDate).toLocaleDateString());

    if (data.location) {
      doc
        .font('Helvetica-Bold')
        .fillColor('#2c3e50')
        .text('Location: ', 50, doc.y, { continued: true })
        .font('Helvetica')
        .fillColor('#34495e')
        .text(data.location.address, { width: 400 });
    }

    doc.moveDown(1.5);
  }

  private addSummary(doc: PDFKit.PDFDocument, data: ReportPDFData): void {
    // Section title
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .fillColor('#2c3e50')
      .text('Report Summary', { underline: true })
      .moveDown(0.8);

    // Overall Performance
    if (data.summary.overallPerformance) {
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor('#3498db')
        .text('Overall Performance')
        .moveDown(0.3);

      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#34495e')
        .text(data.summary.overallPerformance, { align: 'justify', lineGap: 2 })
        .moveDown(1);
    }

    // Key Strengths
    if (data.summary.keyStrengths && data.summary.keyStrengths.length > 0) {
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor('#27ae60')
        .text('Key Strengths')
        .moveDown(0.3);

      data.summary.keyStrengths.forEach((strength, index) => {
        const bulletY = doc.y;
        doc
          .fontSize(10)
          .fillColor('#27ae60')
          .text('✓', 50, bulletY, { continued: false });

        doc
          .fontSize(10)
          .font('Helvetica')
          .fillColor('#34495e')
          .text(strength, 70, bulletY, { width: 475, align: 'justify', lineGap: 2 });

        doc.moveDown(0.5);
      });

      doc.moveDown(0.5);
    }

    // Areas to Focus On
    if (data.summary.areasNeedingAttention && data.summary.areasNeedingAttention.length > 0) {
      // Check if we need a new page
      if (doc.y > 650) {
        doc.addPage();
      }

      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor('#f39c12')
        .text('Areas to Focus On')
        .moveDown(0.3);

      data.summary.areasNeedingAttention.forEach((area, index) => {
        const bulletY = doc.y;
        doc
          .fontSize(10)
          .fillColor('#f39c12')
          .text('▸', 50, bulletY, { continued: false });

        doc
          .fontSize(10)
          .font('Helvetica')
          .fillColor('#34495e')
          .text(area, 70, bulletY, { width: 475, align: 'justify', lineGap: 2 });

        doc.moveDown(0.5);
      });

      doc.moveDown(0.5);
    }

    // Teacher Highlights
    if (data.summary.teacherHighlights && data.summary.teacherHighlights.length > 0) {
      // Check if we need a new page
      if (doc.y > 650) {
        doc.addPage();
      }

      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor('#9b59b6')
        .text('Teacher Highlights')
        .moveDown(0.3);

      data.summary.teacherHighlights.forEach((highlight, index) => {
        const bulletY = doc.y;
        doc
          .fontSize(10)
          .fillColor('#9b59b6')
          .text('💬', 50, bulletY, { continued: false });

        doc
          .fontSize(10)
          .font('Helvetica')
          .fillColor('#34495e')
          .text(highlight, 70, bulletY, { width: 475, align: 'justify', lineGap: 2 });

        doc.moveDown(0.5);
      });
    }

    doc.moveDown(1);
  }

  private addCurrentActivities(doc: PDFKit.PDFDocument, data: ReportPDFData): void {
    // Check if we need a new page
    if (doc.y > 650) {
      doc.addPage();
    }

    // Section title
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor('#2c3e50')
      .text('Current Activities', { underline: true })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#7f8c8d')
      .text(
        `Your child is currently enrolled in the following ${data.currentActivities!.length} activit${data.currentActivities!.length === 1 ? 'y' : 'ies'}:`,
        { align: 'justify' }
      )
      .moveDown(0.8);

    // List current activities
    data.currentActivities!.forEach((activity, index) => {
      const bulletY = doc.y;

      doc
        .fontSize(10)
        .fillColor('#3498db')
        .text('●', 50, bulletY, { continued: false });

      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .fillColor('#2c3e50')
        .text(activity, 70, bulletY, { width: 475 });

      doc.moveDown(0.6);
    });

    doc.moveDown(1);
  }

  private addActivityEvaluations(doc: PDFKit.PDFDocument, data: ReportPDFData): void {
    // Check if we need a new page
    if (doc.y > 650) {
      doc.addPage();
    }

    // Section title
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor('#2c3e50')
      .text('Current Activity Evaluation', { underline: true })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#7f8c8d')
      .text(
        'Based on the report analysis, here is our evaluation of your child\'s current activities:',
        { align: 'justify' }
      )
      .moveDown(1);

    data.currentActivityEvaluations!.forEach((evaluation, index) => {
      // Check if we need a new page
      if (doc.y > 600) {
        doc.addPage();
      }

      // Activity name
      doc
        .fontSize(12)
        .font('Helvetica-Bold')
        .fillColor('#2c3e50')
        .text(`${index + 1}. ${evaluation.activityName}`)
        .moveDown(0.3);

      // Recommendation badge with color
      let badgeColor = '#27ae60'; // green for continue
      let badgeText = '✓ CONTINUE';
      if (evaluation.recommendation === 'reconsider') {
        badgeColor = '#f39c12'; // orange
        badgeText = '⚠ RECONSIDER';
      } else if (evaluation.recommendation === 'stop') {
        badgeColor = '#e74c3c'; // red
        badgeText = '✗ STOP';
      }

      doc
        .fontSize(9)
        .font('Helvetica-Bold')
        .fillColor(badgeColor)
        .text(badgeText, { continued: true })
        .font('Helvetica')
        .fillColor('#7f8c8d')
        .text(`  |  Alignment Score: ${evaluation.alignment}%`)
        .moveDown(0.5);

      // Reasoning
      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#34495e')
        .text(evaluation.reasoning, { align: 'justify', lineGap: 2 })
        .moveDown(0.5);

      // Alternatives (if any)
      if (evaluation.alternatives && evaluation.alternatives.length > 0) {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#3498db')
          .text('Suggested Alternatives:')
          .moveDown(0.2);

        evaluation.alternatives.forEach(alternative => {
          doc
            .fontSize(9)
            .font('Helvetica')
            .fillColor('#34495e')
            .text(`• ${alternative}`, 70, doc.y, { width: 475 });
        });

        doc.moveDown(0.5);
      }

      // Separator line between evaluations
      if (index < data.currentActivityEvaluations!.length - 1) {
        doc
          .strokeColor('#e0e0e0')
          .lineWidth(1)
          .moveTo(50, doc.y + 5)
          .lineTo(545, doc.y + 5)
          .stroke()
          .moveDown(1);
      } else {
        doc.moveDown(0.5);
      }
    });

    doc.moveDown(1);
  }

  private addRecommendations(doc: PDFKit.PDFDocument, data: ReportPDFData): void {
    // New page for recommendations
    doc.addPage();

    // Section title
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .fillColor('#2c3e50')
      .text('Activity Recommendations', { underline: true })
      .moveDown(0.5);

    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#7f8c8d')
      .text(
        `Based on the report analysis, here are ${data.recommendations!.length} personalized activity recommendations:`,
        { align: 'justify' }
      )
      .moveDown(1);

    data.recommendations!.forEach((rec, index) => {
      // Check if we need a new page (roughly estimate space needed)
      if (doc.y > 600) {
        doc.addPage();
      }

      // Activity number and name
      doc
        .fontSize(14)
        .font('Helvetica-Bold')
        .fillColor('#3498db')
        .text(`${index + 1}. ${rec.name}`, { underline: false })
        .moveDown(0.3);

      // Category, Priority, Cost
      doc
        .fontSize(9)
        .font('Helvetica-Bold')
        .fillColor('#7f8c8d')
        .text(`Category: `, { continued: true })
        .font('Helvetica')
        .text(rec.category, { continued: true })
        .font('Helvetica-Bold')
        .text('  |  Priority: ', { continued: true })
        .font('Helvetica')
        .text(rec.priority, { continued: true })
        .font('Helvetica-Bold')
        .text('  |  Cost: ', { continued: true })
        .font('Helvetica')
        .text(rec.estimatedCost);

      doc
        .font('Helvetica-Bold')
        .text('Frequency: ', { continued: true })
        .font('Helvetica')
        .text(rec.frequency)
        .moveDown(0.5);

      // Description
      doc
        .fontSize(10)
        .font('Helvetica')
        .fillColor('#34495e')
        .text(rec.description, { align: 'justify', lineGap: 2 })
        .moveDown(0.5);

      // Why Recommended
      if (rec.whyRecommended) {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#27ae60')
          .text('Why Recommended: ', { continued: true })
          .font('Helvetica')
          .fillColor('#34495e')
          .text(rec.whyRecommended, { align: 'justify', lineGap: 2 })
          .moveDown(0.5);
      }

      // Target Attributes
      if (rec.targetedAttributes && rec.targetedAttributes.length > 0) {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#9b59b6')
          .text('Develops: ', { continued: true })
          .font('Helvetica')
          .fillColor('#34495e')
          .text(rec.targetedAttributes.join(', '))
          .moveDown(0.5);
      }

      // Benefits
      if (rec.benefits && rec.benefits.length > 0) {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#2c3e50')
          .text('Benefits:')
          .moveDown(0.2);

        rec.benefits.forEach(benefit => {
          doc
            .fontSize(9)
            .font('Helvetica')
            .fillColor('#34495e')
            .text(`• ${benefit}`, 70, doc.y, { width: 475 });
        });

        doc.moveDown(0.5);
      }

      // Venues (if available)
      if (rec.venues && rec.venues.length > 0) {
        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#e67e22')
          .text(`Nearby Venues (${rec.venues.length}):`)
          .moveDown(0.2);

        rec.venues.slice(0, 3).forEach(venue => {
          doc
            .fontSize(8)
            .font('Helvetica-Bold')
            .fillColor('#34495e')
            .text(`• ${venue.name}`, 70, doc.y, { continued: true, width: 300 });

          if (venue.distance) {
            doc
              .font('Helvetica')
              .fillColor('#7f8c8d')
              .text(` (${venue.distance})`, { continued: false });
          } else {
            doc.text('');
          }

          doc
            .fontSize(8)
            .font('Helvetica')
            .fillColor('#7f8c8d')
            .text(`  ${venue.address}`, 75, doc.y, { width: 470 });

          if (venue.phone) {
            doc.text(`  ${venue.phone}`, 75, doc.y);
          }
        });

        doc.moveDown(0.3);
      }

      // Separator line between activities
      if (index < data.recommendations!.length - 1) {
        doc
          .strokeColor('#e0e0e0')
          .lineWidth(1)
          .moveTo(50, doc.y + 5)
          .lineTo(545, doc.y + 5)
          .stroke()
          .moveDown(1);
      } else {
        doc.moveDown(0.5);
      }
    });
  }

  private addFooter(doc: PDFKit.PDFDocument): void {
    const pages = doc.bufferedPageRange();

    for (let i = 0; i < pages.count; i++) {
      doc.switchToPage(i);

      // Footer text
      doc
        .fontSize(8)
        .font('Helvetica')
        .fillColor('#95a5a6')
        .text(
          `Generated by Enhance Your Child - ${new Date().toLocaleDateString()}`,
          50,
          doc.page.height - 40,
          { align: 'center', width: doc.page.width - 100 }
        );

      // Page number
      doc.text(
        `Page ${i + 1} of ${pages.count}`,
        50,
        doc.page.height - 25,
        { align: 'center', width: doc.page.width - 100 }
      );
    }
  }
}

export default new PDFGeneratorService();
